export 'package:json_api/src/routing/collection_route.dart';
export 'package:json_api/src/routing/composite_routing.dart';
export 'package:json_api/src/routing/relationship_route.dart';
export 'package:json_api/src/routing/resource_route.dart';
export 'package:json_api/src/routing/route_factory.dart';
export 'package:json_api/src/routing/route_matcher.dart';
export 'package:json_api/src/routing/routing.dart';
export 'package:json_api/src/routing/standard_routes.dart';
export 'package:json_api/src/routing/standard_routing.dart';
